main : com.belmu.uhc.UHC
name : BelmuUHC
author : Belmu
version : 1.0
api-version : 1.8
description : Plugin developed by Belmu. [Ultra Hardcore] | Twitter - @Belmu_
commands :
  info :
    description : Info command.
  start :
    description : Start command.
  heal :
    description : Heal command.
  revive :
    description : Revive command.
  sethost :
    description : Host command.
    aliases : [sh]
  h :
    description : Hide command.
    aliases : [hide]
  forcepvp :
    description : Force PvP command.
    aliases : [fpvp]
  co :
    description : Coordinates command.
  scenarios :
    description : Scenarios command.
    aliases : [sc]